SELECT sc_user_id,
       urn,
       username,
       username_normalized,
       full_name,
       first_name,
       last_name,
       permalink,
       permalink_url,
       avatar_url,
       country,
       city,
       description,
       verified,
       followers_count,
       followings_count,
       tracks_count,
       playlists_count,
       reposts_count,
       comments_count,
       kind,
       sc_created_at,
       sc_last_modified,
       sc_synced_at,
       last_read_at,
       created_at,
       updated_at
FROM users
WHERE urn = $1
