SELECT track.id,
       track.sc_track_id,
       track.urn,
       track.title,
       track.title_normalized,
       track.description,
       track.genre,
       track.tags,
       track.duration_ms,
       track.artwork_url,
       track.permalink_url,
       track.waveform_url,
       track.language,
       track.language_confidence,
       track.isrc,
       track.metadata_artist,
       track.sharing,
       track.sc_metadata,
       track.deleted_at,
       track.sc_created_at,
       track.sc_last_modified,
       track.release_year,
       track.release_date,
       track.uploader_sc_user_id,
       track.uploader_urn,
       track.uploader_username,
       track.uploader_avatar_url,
       track.primary_artist_id,
       track.album_id,
       track.album_position,
       track.canonical_track_id,
       track.cover_of_artist_id,
       track.upload_kind,
       track.audio_fingerprint,
       track.quality_score,
       track.play_count_sc,
       track.likes_count_sc,
       track.reposts_count_sc,
       track.comments_count_sc,
       track.enrich_state,
       track.enrich_attempts,
       track.enrich_source,
       track.enrich_confidence,
       track.enriched_at,
       track.index_state,
       track.index_priority,
       track.index_attempts,
       track.indexed_at,
       track.storage_state,
       track.storage_priority,
       track.storage_quality,
       track.storage_attempts,
       track.s3_verified_at,
       track.s3_missing_at,
       track.hq_upgrade_pending,
       track.hq_upgrade_attempts,
       track.hq_upgrade_last_at,
       track.needs_duration_resolve,
       track.sc_synced_at,
       track.last_read_at,
       track.created_at,
       track.updated_at
FROM (SELECT DISTINCT ON (serving.id) serving.id,
                                      requested.slot
      FROM unnest($1::uuid[]) WITH ORDINALITY AS requested(id, slot)
      JOIN tracks AS asked ON asked.id = requested.id
      JOIN tracks AS serving ON serving.id = coalesce(asked.superseded_by, asked.id)
      WHERE serving.sharing = 'public'
        AND serving.deleted_at IS NULL
        AND serving.superseded_by IS NULL
      ORDER BY serving.id, requested.slot) AS kept
JOIN tracks AS track ON track.id = kept.id
ORDER BY kept.slot
