INSERT INTO playlists (
    urn,
    sc_playlist_id,
    title,
    title_normalized,
    description,
    genre,
    tags,
    artwork_url,
    permalink_url,
    owner_sc_user_id,
    owner_urn,
    owner_username,
    track_count,
    duration_ms,
    playlist_type,
    kind,
    sharing,
    release_year,
    release_date,
    label_name,
    likes_count_sc,
    reposts_count_sc,
    sc_created_at,
    sc_last_modified,
    sc_synced_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5, ''),
    NULLIF($6, ''),
    $7,
    NULLIF($8, ''),
    NULLIF($9, ''),
    NULLIF($10, ''),
    NULLIF($11, ''),
    NULLIF($12, ''),
    $13,
    NULLIF($14::bigint, -1::bigint),
    NULLIF($15, ''),
    NULLIF($16, ''),
    $17,
    NULLIF($18::smallint, 0::smallint),
    NULLIF($19, '')::date,
    NULLIF($20, ''),
    NULLIF($21::bigint, -1::bigint),
    NULLIF($22::bigint, -1::bigint),
    NULLIF($23, '')::timestamptz,
    NULLIF($24, '')::timestamptz,
    now()
)
ON CONFLICT (urn) DO NOTHING
