use crate::error::AppError;
use serde_json::Value;

/// 403 + body содержит маркеры CloudFront/Cloudflare ban — означает что SC
/// (или его CDN) временно заблокировал источник, ретрай через секунды
/// бесполезен. Воркер sync_queue по этому маркеру не инкрементит retry_count
/// и откладывает строку на длинный backoff.
pub fn is_ban_error(err: &AppError) -> bool {
    let AppError::ScApi { status, body } = err else {
        return false;
    };
    if *status != 403 {
        return false;
    }
    let body_str = match body {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    };
    let lower = body_str.to_lowercase();
    lower.contains("request blocked")
        || lower.contains("the request could not be satisfied")
        || lower.contains("generated by cloudfront")
}

/// 429 либо текстовый маркер rate-limit от SC. Семантически как ban —
/// перерыв нужен длинный, но триггер другой.
pub fn is_rate_limited(err: &AppError) -> bool {
    match err {
        AppError::ScApi { status: 429, .. } => true,
        AppError::ScApi { body, .. } => {
            let s = match body {
                Value::String(v) => v.to_lowercase(),
                other => other.to_string().to_lowercase(),
            };
            s.contains("rate limit") || s.contains("too many requests")
        }
        _ => false,
    }
}

/// SC-токен-эндпоинт ответил 400/401 — грант/refresh_token отвергнут, нужен
/// ре-логин. В отличие от транзиентных сбоев роута (`ScUnreachable`/5xx/сеть),
/// которые НЕ требуют ре-логина: токен-эндпоинт не отдаёт 400/401 при недоступности.
pub fn is_invalid_grant(err: &AppError) -> bool {
    matches!(err, AppError::ScApi { status: 400 | 401, .. })
}
