use crate::error::AppError;
use serde_json::Value;

pub const RETRY_AFTER_MAX_SECONDS: i64 = 3600;

pub fn is_ban_error(err: &AppError) -> bool {
    let AppError::ScApi { status, body, .. } = err else {
        return false;
    };
    if *status != 403 {
        return false;
    }
    let body_str = match body {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    };
    let lower = body_str.to_lowercase();
    lower.contains("request blocked")
        || lower.contains("the request could not be satisfied")
        || lower.contains("generated by cloudfront")
}

pub fn is_rate_limited(err: &AppError) -> bool {
    match err {
        AppError::SoundCloudRefreshRateLimited { .. } => true,
        AppError::ScApi { status: 429, .. } => true,
        AppError::ScApi { body, .. } => {
            let s = match body {
                Value::String(v) => v.to_lowercase(),
                other => other.to_string().to_lowercase(),
            };
            s.contains("rate limit") || s.contains("too many requests")
        }
        _ => false,
    }
}

pub fn is_invalid_grant(err: &AppError) -> bool {
    let AppError::ScApi {
        status: 400 | 401,
        body,
        ..
    } = err
    else {
        return false;
    };
    contains_oauth_error(body, "invalid_grant")
}

pub fn is_app_credentials_error(err: &AppError) -> bool {
    let AppError::ScApi {
        status: 400 | 401,
        body,
        ..
    } = err
    else {
        return false;
    };
    contains_oauth_error(body, "invalid_client")
        || contains_oauth_error(body, "unauthorized_client")
}

pub fn is_upstream_failure(err: &AppError) -> bool {
    matches!(err, AppError::ScApi { status, .. } if *status >= 500)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScFailure {
    Ban,
    Credentials,
    InvalidGrant,
    RateLimited,
    Upstream,
    Unreachable,
    Other,
}

impl ScFailure {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Ban => "ban",
            Self::Credentials => "credentials",
            Self::InvalidGrant => "invalid_grant",
            Self::RateLimited => "rate_limited",
            Self::Upstream => "upstream_5xx",
            Self::Unreachable => "unreachable",
            Self::Other => "other",
        }
    }
}

pub fn classify(err: &AppError) -> ScFailure {
    if is_ban_error(err) {
        ScFailure::Ban
    } else if is_app_credentials_error(err) {
        ScFailure::Credentials
    } else if is_invalid_grant(err) {
        ScFailure::InvalidGrant
    } else if is_rate_limited(err) {
        ScFailure::RateLimited
    } else if is_upstream_failure(err) {
        ScFailure::Upstream
    } else if matches!(
        err,
        AppError::ScUnreachable(_) | AppError::Http(_) | AppError::ScDeadlineExceeded
    ) {
        ScFailure::Unreachable
    } else {
        ScFailure::Other
    }
}

pub fn retry_after_seconds(err: &AppError) -> Option<i64> {
    let seconds = match err {
        AppError::ScApi {
            retry_after_sec, ..
        } => *retry_after_sec,
        AppError::SoundCloudRefreshRateLimited { retry_after_sec } => Some(*retry_after_sec),
        _ => None,
    };
    seconds.map(|seconds| seconds.clamp(1, RETRY_AFTER_MAX_SECONDS))
}

fn contains_oauth_error(value: &Value, expected: &str) -> bool {
    match value {
        Value::String(value) => value
            .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
            .any(|part| part.eq_ignore_ascii_case(expected)),
        Value::Array(values) => values
            .iter()
            .any(|value| contains_oauth_error(value, expected)),
        Value::Object(values) => values.iter().any(|(key, value)| {
            matches!(
                key.as_str(),
                "error" | "code" | "error_code" | "error_description"
            ) && contains_oauth_error(value, expected)
        }),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn recognizes_invalid_grant() {
        let error = AppError::ScApi {
            status: 400,
            body: json!({
                "error": "invalid_grant",
                "error_description": "Refresh token is no longer valid"
            }),
            retry_after_sec: None,
        };

        assert!(is_invalid_grant(&error));
    }

    #[test]
    fn does_not_treat_invalid_client_as_invalid_grant() {
        let error = AppError::ScApi {
            status: 401,
            body: json!({ "error": "invalid_client" }),
            retry_after_sec: None,
        };

        assert!(!is_invalid_grant(&error));
    }

    #[test]
    fn does_not_guess_from_status_without_an_oauth_error() {
        let error = AppError::ScApi {
            status: 400,
            body: json!({ "message": "bad request" }),
            retry_after_sec: None,
        };

        assert!(!is_invalid_grant(&error));
    }

    #[test]
    fn recognizes_app_credentials_failures() {
        let error = AppError::ScApi {
            status: 401,
            body: json!({ "error": "invalid_client" }),
            retry_after_sec: None,
        };

        assert!(is_app_credentials_error(&error));
    }

    #[test]
    fn preserves_upstream_retry_after_up_to_the_policy_ceiling() {
        let inside = AppError::ScApi {
            status: 429,
            body: Value::Null,
            retry_after_sec: Some(900),
        };
        assert_eq!(retry_after_seconds(&inside), Some(900));
    }

    #[test]
    fn an_absurd_upstream_retry_after_cannot_outlive_our_own_policy() {
        for absurd in [RETRY_AFTER_MAX_SECONDS + 1, 10_000_000, i64::MAX] {
            let error = AppError::ScApi {
                status: 429,
                body: Value::Null,
                retry_after_sec: Some(absurd),
            };
            assert_eq!(retry_after_seconds(&error), Some(RETRY_AFTER_MAX_SECONDS));
        }
        let negative = AppError::soundcloud_refresh_rate_limited(-5);
        assert_eq!(retry_after_seconds(&negative), Some(1));
    }

    fn ban_page(body: &str) -> AppError {
        AppError::ScApi {
            status: 403,
            body: Value::String(body.to_owned()),
            retry_after_sec: None,
        }
    }

    #[test]
    fn every_known_ban_page_is_recognized() {
        for page in [
            "<html><body>Request blocked</body></html>",
            "The request could not be satisfied.",
            "Generated by cloudfront (CloudFront)",
        ] {
            assert!(is_ban_error(&ban_page(page)), "{page}");
        }
    }

    #[test]
    fn an_ordinary_refusal_is_not_a_ban() {
        assert!(!is_ban_error(&ban_page("this playlist is private")));
        assert!(!is_ban_error(&AppError::ScApi {
            status: 404,
            body: Value::String("Request blocked".to_owned()),
            retry_after_sec: None,
        }));
        assert!(!is_ban_error(&AppError::ScUnreachable("gone".to_owned())));
    }

    #[test]
    fn upstream_failures_are_classified_once_for_every_caller() {
        for status in [500_u16, 502, 503, 504] {
            let error = AppError::ScApi {
                status,
                body: Value::Null,
                retry_after_sec: None,
            };
            assert!(is_upstream_failure(&error), "{status}");
        }
        for status in [400_u16, 401, 403, 404, 429] {
            let error = AppError::ScApi {
                status,
                body: Value::Null,
                retry_after_sec: None,
            };
            assert!(!is_upstream_failure(&error), "{status}");
        }
        assert!(!is_upstream_failure(&AppError::ScUnreachable(
            "gone".to_owned()
        )));
    }

    fn api_error(status: u16, body: Value) -> AppError {
        AppError::ScApi {
            status,
            body,
            retry_after_sec: None,
        }
    }

    #[test]
    fn every_failure_lands_on_exactly_one_class() {
        let cases: [(AppError, ScFailure); 8] = [
            (
                api_error(403, json!("<html><body>Request blocked</body></html>")),
                ScFailure::Ban,
            ),
            (
                api_error(401, json!({ "error": "invalid_client" })),
                ScFailure::Credentials,
            ),
            (
                api_error(400, json!({ "error": "invalid_grant" })),
                ScFailure::InvalidGrant,
            ),
            (api_error(429, Value::Null), ScFailure::RateLimited),
            (api_error(503, Value::Null), ScFailure::Upstream),
            (
                AppError::ScUnreachable("offline".to_owned()),
                ScFailure::Unreachable,
            ),
            (AppError::ScDeadlineExceeded, ScFailure::Unreachable),
            (api_error(404, Value::Null), ScFailure::Other),
        ];

        for (error, expected) in cases {
            assert_eq!(classify(&error), expected, "{error}");
        }
    }

    #[test]
    fn a_ban_is_a_ban_and_not_merely_a_credentials_problem() {
        let ban = api_error(
            403,
            json!("The request could not be satisfied. unauthorized_client"),
        );

        assert_eq!(
            classify(&ban),
            ScFailure::Ban,
            "the order of the classifiers decides which label an error gets"
        );
    }

    #[test]
    fn every_class_has_a_stable_name() {
        let names: Vec<&str> = [
            ScFailure::Ban,
            ScFailure::Credentials,
            ScFailure::InvalidGrant,
            ScFailure::RateLimited,
            ScFailure::Upstream,
            ScFailure::Unreachable,
            ScFailure::Other,
        ]
        .into_iter()
        .map(ScFailure::as_str)
        .collect();

        assert_eq!(
            names,
            [
                "ban",
                "credentials",
                "invalid_grant",
                "rate_limited",
                "upstream_5xx",
                "unreachable",
                "other"
            ]
        );
    }
}
